vich_uploader:
    db_driver: orm

    metadata:
        type: annotation

    mappings:
       profiles:
           uri_prefix: /images/profiles
           upload_destination: '%kernel.project_dir%/public/images/profiles'
